import { Producer, Product, Order } from '../lib/types';

export const SEED_PRODUCERS: Producer[] = [
  {
    id: 'prod-maelstrom',
    name: 'Maelstrom Roasters',
    slug: 'maelstrom-roasters-zurich',
    tagline: 'Specialty Coffee & On-Demand Micro-Roasting',
    category: 'coffee',
    country: 'CH',
    city: 'Zürich',
    currency: 'CHF',
    bio: 'Wir rösten handwerkliche Kaffeespezialitäten in Zürich-West. Unsere Bohnen stammen aus direktem Handel mit Kleinbauern und werden auf unserer Giesen W6A erst nach Eingang Ihrer individuellen Rezeptur frisch chargiert.',
    heroImage: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80',
    logoText: 'MÆLSTROM ROASTERS — ZÜRICH',
    vatNumber: 'CHE-412.890.123 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Röstung jeden Dienstag & Donnerstag, Versand Folgetag',
    batchScheduleNotice: 'Nächste Röstcharge: Dienstag 08:00 Uhr',
    establishedYear: 2021,
  },
  {
    id: 'prod-aarau-hops',
    name: 'Aarau Hops & Grain',
    slug: 'aarau-hops-and-grain',
    tagline: 'Unfiltered Microbrews & Custom Curated Crates',
    category: 'beer',
    country: 'CH',
    city: 'Aarau',
    currency: 'CHF',
    bio: 'Unfiltrierte, charakterstarke Biere aus dem Aargau. Wählen Sie Ihre 6 Lieblingsstile oder lassen Sie sich eine massgeschneiderte Probierkiste mit individuellem Flaschenetikett und Holzkiste frisch zusammenstellen.',
    heroImage: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=1200&q=80',
    logoText: 'AARAU HOPS & GRAIN — MICROBREWERY',
    vatNumber: 'CHE-298.114.772 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Abfüllung & Frischeversand wöchentlich freitags',
    batchScheduleNotice: 'Frische Zapfung & Versand: Freitag',
    establishedYear: 2019,
  },
  {
    id: 'prod-cacao-basel',
    name: 'Cacao Atelier Basel',
    slug: 'cacao-atelier-basel',
    tagline: 'Bean-to-Bar Chocolate & Bespoke Grand Cru Infusions',
    category: 'chocolate',
    country: 'CH',
    city: 'Basel',
    currency: 'CHF',
    bio: 'Feinste Bean-to-Bar Schokoladen mit sortenreinen Edelkakaos. Stellen Sie Ihren eigenen Kakaogehalt und die Edeltropfen-Inklusionen mit persönlicher Banderole für Kenner zusammen.',
    heroImage: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=1200&q=80',
    logoText: 'CACAO ATELIER — BASEL',
    vatNumber: 'CHE-119.553.901 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Temperierung & Giessen dienstags, Versand mittwochs',
    batchScheduleNotice: 'Giesstermin nächste Charge: Dienstag',
    establishedYear: 2022,
  },
];

export const SEED_PRODUCTS: Product[] = [
  // 1. Maelstrom Coffee Custom Blend
  {
    id: 'prod-coffee-custom-blend',
    producerId: 'prod-maelstrom',
    title: 'Signature Custom Coffee Blend (500g)',
    subtitle: 'Kreieren Sie Ihren persönlichen Blend mit Live-Etikett',
    description: 'Kombinieren Sie 4 erstklassige Single Origins per Schieberegler exakt nach Ihrem Geschmacksprofil. Wir wiegen die Rohkaffees auf das Gramm genau ab und rösten sie frisch mit Ihrem persönlichen Etikett.',
    category: 'coffee',
    basePrice: 22.00,
    unitText: '500g Ventilbeutel',
    weightGrams: 500,
    isCustomizable: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['Made to Order', 'Single Origin Blend', 'Spezialitätenkaffee', 'Direct Trade'],
    config: {
      id: 'cfg-coffee-blend',
      productId: 'prod-coffee-custom-blend',
      type: 'blend_or_mix',
      targetTotalPercent: 100,
      totalWeightGrams: 500,
      components: [
        {
          id: 'c-ethiopia',
          name: 'Äthiopien Yirgacheffe G1',
          origin: 'Yirgacheffe, 2\'050 m.ü.M.',
          process: 'Washed / Heirloom',
          notes: ['Bergamotte', 'Jasmin', 'Pfirsich'],
          maxRatio: 100,
          priceMultiplier: 1.15,
          color: '#E0A96D',
          inStock: true,
        },
        {
          id: 'c-colombia',
          name: 'Kolumbien Huila Supremo',
          origin: 'San Agustín, 1\'750 m.ü.M.',
          process: 'Washed / Castillo',
          notes: ['Roter Apfel', 'Karamell', 'Milchschokolade'],
          maxRatio: 100,
          priceMultiplier: 1.05,
          color: '#A65335',
          inStock: true,
        },
        {
          id: 'c-brazil',
          name: 'Brasilien Cerrado Dulce',
          origin: 'Minas Gerais, 1\'150 m.ü.M.',
          process: 'Natural / Bourbon',
          notes: ['Haselnuss', 'Kakao', 'Cremiger Körper'],
          maxRatio: 100,
          priceMultiplier: 0.95,
          color: '#633A26',
          inStock: true,
        },
        {
          id: 'c-guatemala',
          name: 'Guatemala Antigua Pastoral',
          origin: 'Volcano Valley, 1\'600 m.ü.M.',
          process: 'Washed / Caturra',
          notes: ['Dunkle Beeren', 'Marzipan', 'Zimt'],
          maxRatio: 100,
          priceMultiplier: 1.10,
          color: '#3F2212',
          inStock: true,
        },
      ],
      options: [
        {
          key: 'grind',
          title: 'Mahlgrad & Zubereitung',
          type: 'pills',
          defaultValue: 'whole_bean',
          values: [
            { label: 'Ganze Bohne (Frisch)', value: 'whole_bean', description: 'Optimale Frische' },
            { label: 'Espresso (Siebträger)', value: 'espresso', description: 'Fein & cremig' },
            { label: 'Bialetti (Moka)', value: 'moka', description: 'Mittel-fein' },
            { label: 'Filter (V60 / Chemex)', value: 'filter', description: 'Mittel' },
            { label: 'French Press / Cold Brew', value: 'french_press', description: 'Grob' },
          ],
        },
        {
          key: 'roast_profile',
          title: 'Röstprofil',
          type: 'pills',
          defaultValue: 'omni_medium',
          values: [
            { label: 'Nordic Light Roast (Fruchtig & Klar)', value: 'light_nordic' },
            { label: 'Omni Medium Roast (Balanciert & Süss)', value: 'omni_medium' },
            { label: 'Italian Dark Roast (Kräftig & Schokoladig)', value: 'dark_italian' },
          ],
        },
      ],
      labelCustomization: {
        allowed: true,
        maxTitleLength: 28,
        maxDedicationLength: 45,
        templateType: 'coffee_bag',
        fontStyles: [
          { id: 'swiss-sans', label: 'Swiss Neo-Grotesk', fontFamily: 'Inter, sans-serif', styleClass: 'font-sans uppercase tracking-widest font-semibold' },
          { id: 'editorial-serif', label: 'Zurich Heritage Serif', fontFamily: 'Playfair Display, serif', styleClass: 'font-serif italic tracking-normal' },
          { id: 'minimal-mono', label: 'Atelier Technical Mono', fontFamily: 'JetBrains Mono, monospace', styleClass: 'font-mono font-medium tracking-tight' },
        ],
        badgeOptions: ['Limited Batch', 'Private Reserve', 'House Roast', 'Master Blend'],
      },
    },
  },
  // Maelstrom Standard Product
  {
    id: 'prod-coffee-standard-geisha',
    producerId: 'prod-maelstrom',
    title: 'Panama Boquete Geisha Lot #4',
    subtitle: 'Limitierte Rarität mit floralem Jasmin-Bouquet',
    description: 'Sortenreiner Geisha-Kaffee aus Panama mit aussergewöhnlicher Klarheit und Jasmin-Noten.',
    category: 'coffee',
    basePrice: 34.00,
    unitText: '250g Box',
    weightGrams: 250,
    isCustomizable: false,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80'],
    tags: ['Micro-Lot', 'Single Origin', 'Competition Grade'],
  },

  // 2. Aarau Craft Beer Box
  {
    id: 'prod-beer-custom-box',
    producerId: 'prod-aarau-hops',
    title: 'Curated 6er Craft Beer Flight & Custom Label',
    subtitle: 'Stellen Sie Ihre 6 Lieblingsflaschen zusammen',
    description: 'Wählen Sie die 6 Flaschen Ihrer Box aus unseren frisch gebrauten Suden. Inklusive individuellem Flaschenetikett und Präsentbox.',
    category: 'beer',
    basePrice: 28.50,
    unitText: '6x 330ml Box',
    weightGrams: 1980,
    isCustomizable: true,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1608270199182-96541f53fa38?auto=format&fit=crop&w=800&q=80'],
    tags: ['Craft Beer', 'Unfiltriert', 'Aargau', 'Handbrauerei'],
    config: {
      id: 'cfg-beer-box',
      productId: 'prod-beer-custom-box',
      type: 'blend_or_mix',
      targetTotalPercent: 100, // Represented as 6 bottles = 100% (or ratio per style)
      totalWeightGrams: 6,
      components: [
        {
          id: 'b-hazy-ipa',
          name: 'Aare Hazy Double IPA (7.2%)',
          origin: 'Citra & Mosaic Dry Hop',
          notes: ['Maracuja', 'Grapefruit', 'Cremig trüb'],
          maxRatio: 100,
          priceMultiplier: 1.12,
          color: '#EBB344',
          inStock: true,
        },
        {
          id: 'b-session-pale',
          name: 'Kettenbrücke Session Pale (4.8%)',
          origin: 'Cascade & Hallertau Blanc',
          notes: ['Stachelbeere', 'Frisches Gras', 'Süffig'],
          maxRatio: 100,
          priceMultiplier: 0.95,
          color: '#F4D06F',
          inStock: true,
        },
        {
          id: 'b-sour-cherry',
          name: 'Jura Wild Sour Cherry (5.5%)',
          origin: 'Spontanvergärung & Aargauer Sauerkirschen',
          notes: ['Sauerkirsche', 'Holzfass', 'Erfrischend trocken'],
          maxRatio: 100,
          priceMultiplier: 1.20,
          color: '#9C2E35',
          inStock: true,
        },
        {
          id: 'b-smoked-porter',
          name: 'Altstadt Smoked Imperial Porter (6.8%)',
          origin: 'Buchenrauchmalz & Kakaobohnen',
          notes: ['Rauch', 'Bitterschokolade', 'Espresso'],
          maxRatio: 100,
          priceMultiplier: 1.05,
          color: '#261C14',
          inStock: true,
        },
      ],
      options: [
        {
          key: 'packaging',
          title: 'Verpackungsausführung',
          type: 'pills',
          defaultValue: 'kraft_box',
          values: [
            { label: 'Design Kraftkarton Box (Inklusive)', value: 'kraft_box' },
            { label: 'Rustikale Schweizer Holzkiste (+ CHF 8.00)', value: 'wood_crate', priceDelta: 8.00 },
          ],
        },
      ],
      labelCustomization: {
        allowed: true,
        maxTitleLength: 25,
        maxDedicationLength: 40,
        templateType: 'beer_bottle',
        fontStyles: [
          { id: 'swiss-sans', label: 'Swiss Modern', fontFamily: 'Inter, sans-serif', styleClass: 'font-sans uppercase font-bold tracking-wider' },
          { id: 'minimal-mono', label: 'Brewery Batch Mono', fontFamily: 'JetBrains Mono, monospace', styleClass: 'font-mono font-medium' },
          { id: 'editorial-serif', label: 'Tavern Serif', fontFamily: 'Playfair Display, serif', styleClass: 'font-serif italic' },
        ],
        badgeOptions: ['Braumeister Edition', 'Private Crate', 'Event Sud', 'Frisch Gezapft'],
      },
    },
  },

  // 3. Cacao Atelier Basel Grand Cru
  {
    id: 'prod-chocolate-custom',
    producerId: 'prod-cacao-basel',
    title: 'Bespoke Grand Cru Schokoladentafel (100g)',
    subtitle: 'Wunsch-Kakaogehalt & Edelinversionen frisch gegossen',
    description: 'Gestalten Sie Ihre persönliche Tafel aus Edelkakaos aus Madagaskar & Ecuador. Wählen Sie Textur, Salzkristalle und Kakaonibs mit vergoldetem Banderolen-Etikett.',
    category: 'chocolate',
    basePrice: 14.50,
    unitText: '100g Bar in Pergamin',
    weightGrams: 100,
    isCustomizable: true,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=800&q=80'],
    tags: ['Bean-to-Bar', 'Bio & Fair', 'Basel', 'Handgegossen'],
    config: {
      id: 'cfg-chocolate-custom',
      productId: 'prod-chocolate-custom',
      type: 'blend_or_mix',
      targetTotalPercent: 100,
      totalWeightGrams: 100,
      components: [
        {
          id: 'ch-madagascar',
          name: 'Madagaskar Sambirano 72%',
          origin: 'Akesson Estate / Single Valley',
          notes: ['Rote Johannisbeere', 'Zitrusnoten', 'Helle Frucht'],
          maxRatio: 100,
          priceMultiplier: 1.10,
          color: '#4B2A1E',
          inStock: true,
        },
        {
          id: 'ch-ecuador',
          name: 'Ecuador Hacienda Victoria 80%',
          origin: 'Guayas / Arriba Nacional',
          notes: ['Floral', 'Dunkler Honig', 'Nussig'],
          maxRatio: 100,
          priceMultiplier: 1.05,
          color: '#321911',
          inStock: true,
        },
        {
          id: 'ch-peru',
          name: 'Peru Chuncho Criollo 65%',
          origin: 'Cusco Valley / Ur-Kakao',
          notes: ['Banane', 'Passionsfrucht', 'Karamell'],
          maxRatio: 100,
          priceMultiplier: 1.15,
          color: '#5C3828',
          inStock: true,
        },
      ],
      options: [
        {
          key: 'inclusions',
          title: 'Veredelung & Toppings',
          type: 'pills',
          defaultValue: 'fleur_de_sel',
          values: [
            { label: 'Fleur de Sel de Guérande', value: 'fleur_de_sel' },
            { label: 'Geröstete Kakaonibs & Chili', value: 'nibs_chili', priceDelta: 1.50 },
            { label: 'Piemonteser Haselnuss-Krokant', value: 'hazelnut', priceDelta: 2.00 },
            { label: 'Pur (Ohne Zugaben)', value: 'pure' },
          ],
        },
      ],
      labelCustomization: {
        allowed: true,
        maxTitleLength: 26,
        maxDedicationLength: 45,
        templateType: 'chocolate_wrap',
        fontStyles: [
          { id: 'editorial-serif', label: 'Basel Grand Cru Serif', fontFamily: 'Playfair Display, serif', styleClass: 'font-serif italic tracking-wide' },
          { id: 'swiss-sans', label: 'Swiss Modern', fontFamily: 'Inter, sans-serif', styleClass: 'font-sans uppercase tracking-widest' },
          { id: 'minimal-mono', label: 'Atelier Artisan Mono', fontFamily: 'JetBrains Mono, monospace', styleClass: 'font-mono' },
        ],
        badgeOptions: ['Grand Cru 2026', 'Limited Pour', 'Single Terroir', 'Chef\'s Reserve'],
      },
    },
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'ATL-2026-8801',
    producerId: 'prod-maelstrom',
    producerName: 'Maelstrom Roasters',
    customer: {
      name: 'Marc Oberholzer',
      email: 'marc.oberholzer@bluewin.ch',
      street: 'Hardturmstrasse 130',
      postalCode: '8005',
      city: 'Zürich',
      country: 'CH',
    },
    items: [
      {
        id: 'item-1',
        productId: 'prod-coffee-custom-blend',
        productTitle: 'Signature Custom Coffee Blend (500g)',
        quantity: 2,
        unitPrice: 24.20,
        totalPrice: 48.40,
        weightGrams: 500,
        recipe: [
          { componentId: 'c-ethiopia', componentName: 'Äthiopien Yirgacheffe G1', origin: 'Yirgacheffe', ratio: 60, grams: 300 },
          { componentId: 'c-colombia', componentName: 'Kolumbien Huila Supremo', origin: 'San Agustín', ratio: 40, grams: 200 },
        ],
        selections: {
          grind: 'espresso',
          roast_profile: 'omni_medium',
        },
        customLabel: {
          headline: 'Marc’s Morning Fuel',
          subtitle: '60% Yirgacheffe / 40% Huila',
          dedication: 'Frisch geröstet für das Team Zürich-West',
          fontStyle: 'swiss-sans',
          batchNumber: 'MZ-BATCH #441',
          roastOrBrewDate: '19.08.2026',
        },
      },
    ],
    status: 'in_production',
    currency: 'CHF',
    subtotal: 48.40,
    taxRate: 0.081,
    taxAmount: 3.92,
    total: 48.40,
    fulfillmentType: 'shipping',
    paymentMethod: 'twint',
    paymentStatus: 'paid',
    createdAt: '2026-08-15T14:22:00Z',
    scheduledBatchDate: '2026-08-18',
  },
  {
    id: 'ord-1002',
    orderNumber: 'ATL-2026-8802',
    producerId: 'prod-maelstrom',
    producerName: 'Maelstrom Roasters',
    customer: {
      name: 'Elena Rossi',
      email: 'elena.rossi@ticino.com',
      street: 'Via Nassa 12',
      postalCode: '6900',
      city: 'Lugano',
      country: 'CH',
    },
    items: [
      {
        id: 'item-2',
        productId: 'prod-coffee-custom-blend',
        productTitle: 'Signature Custom Coffee Blend (500g)',
        quantity: 1,
        unitPrice: 23.50,
        totalPrice: 23.50,
        weightGrams: 500,
        recipe: [
          { componentId: 'c-brazil', componentName: 'Brasilien Cerrado Dulce', origin: 'Minas Gerais', ratio: 70, grams: 350 },
          { componentId: 'c-guatemala', componentName: 'Guatemala Antigua Pastoral', origin: 'Volcano Valley', ratio: 30, grams: 150 },
        ],
        selections: {
          grind: 'whole_bean',
          roast_profile: 'dark_italian',
        },
        customLabel: {
          headline: 'Bar Italia Reserve',
          subtitle: '70% Cerrado / 30% Antigua',
          dedication: 'Caffè per la Domenica',
          fontStyle: 'editorial-serif',
          batchNumber: 'MZ-BATCH #442',
          roastOrBrewDate: '19.08.2026',
        },
      },
    ],
    status: 'paid',
    currency: 'CHF',
    subtotal: 23.50,
    taxRate: 0.081,
    taxAmount: 1.90,
    total: 23.50,
    fulfillmentType: 'shipping',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    createdAt: '2026-08-15T18:05:00Z',
    scheduledBatchDate: '2026-08-18',
  },
  {
    id: 'ord-1003',
    orderNumber: 'ATL-2026-8803',
    producerId: 'prod-aarau-hops',
    producerName: 'Aarau Hops & Grain',
    customer: {
      name: 'Simon Frei',
      email: 'simon.frei@gmx.ch',
      street: 'Bahnhofstrasse 8',
      postalCode: '5000',
      city: 'Aarau',
      country: 'CH',
    },
    items: [
      {
        id: 'item-3',
        productId: 'prod-beer-custom-box',
        productTitle: 'Curated 6er Craft Beer Flight & Custom Label',
        quantity: 1,
        unitPrice: 29.80,
        totalPrice: 29.80,
        weightGrams: 1980,
        recipe: [
          { componentId: 'b-hazy-ipa', componentName: 'Aare Hazy Double IPA', origin: 'Citra/Mosaic', ratio: 50, grams: 3 },
          { componentId: 'b-sour-cherry', componentName: 'Jura Wild Sour Cherry', origin: 'Aargau Cherries', ratio: 50, grams: 3 },
        ],
        selections: {
          packaging: 'kraft_box',
        },
        customLabel: {
          headline: 'Summer Solstice Sud #08',
          subtitle: '3x Hazy DIPA / 3x Wild Sour',
          dedication: 'Für das Grillfest am Aareufer',
          fontStyle: 'minimal-mono',
          batchNumber: 'AHG-CRATE #112',
          roastOrBrewDate: '21.08.2026',
        },
      },
    ],
    status: 'ready_for_pickup',
    currency: 'CHF',
    subtotal: 29.80,
    taxRate: 0.081,
    taxAmount: 2.41,
    total: 29.80,
    fulfillmentType: 'pickup',
    paymentMethod: 'twint',
    paymentStatus: 'paid',
    createdAt: '2026-08-14T11:10:00Z',
    scheduledBatchDate: '2026-08-21',
  },
];
