import { Producer, Product, Order } from '../lib/types';

export const SEED_PRODUCERS: Producer[] = [
  {
    id: 'prod-maelstrom',
    name: 'Maelstrom Roasters',
    slug: 'maelstrom-roasters-zurich',
    tagline: 'Specialty Coffee & On-Demand Micro-Roasting',
    category: 'coffee',
    country: 'CH',
    city: 'Zürich',
    currency: 'CHF',
    bio: 'Wir rösten handwerkliche Kaffeespezialitäten in Zürich-West. Unsere Bohnen stammen aus direktem Handel mit Kleinbauern und werden auf unserer Giesen W6A erst nach Eingang Ihrer individuellen Rezeptur frisch chargiert.',
    heroImage: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80',
    logoText: 'MÆLSTROM ROASTERS — ZÜRICH',
    vatNumber: 'CHE-412.890.123 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Röstung jeden Dienstag & Donnerstag, Versand Folgetag',
    batchScheduleNotice: 'Nächste Röstcharge: Dienstag 08:00 Uhr',
    establishedYear: 2021,
    contactEmail: 'roastmaster@maelstrom.ch',
    capacityPerBatch: 40,
  },
  {
    id: 'prod-aarau-hops',
    name: 'Aarau Hops & Grain',
    slug: 'aarau-hops-and-grain',
    tagline: 'Unfiltered Microbrews & Custom Curated Crates',
    category: 'beer',
    country: 'CH',
    city: 'Aarau',
    currency: 'CHF',
    bio: 'Unfiltrierte, charakterstarke Biere aus dem Aargau. Wählen Sie Ihre 6 Lieblingsstile oder lassen Sie sich eine massgeschneiderte Probierkiste mit individuellem Flaschenetikett frisch zusammenstellen.',
    heroImage: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=1200&q=80',
    logoText: 'AARAU HOPS & GRAIN — MICROBREWERY',
    vatNumber: 'CHE-298.114.772 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Abfüllung & Frischeversand wöchentlich freitags',
    batchScheduleNotice: 'Frische Zapfung & Versand: Freitag',
    establishedYear: 2019,
    contactEmail: 'brauerei@aarauhops.ch',
    capacityPerBatch: 25,
  },
  {
    id: 'prod-cacao-basel',
    name: 'Cacao Atelier Basel',
    slug: 'cacao-atelier-basel',
    tagline: 'Bean-to-Bar Chocolate & Bespoke Grand Cru Infusions',
    category: 'chocolate',
    country: 'CH',
    city: 'Basel',
    currency: 'CHF',
    bio: 'Feinste Bean-to-Bar Schokoladen mit sortenreinen Edelkakaos. Stellen Sie Ihren eigenen Kakaogehalt und die Edeltropfen-Inklusionen mit persönlicher Banderole für Kenner zusammen.',
    heroImage: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=1200&q=80',
    logoText: 'CACAO ATELIER — BASEL',
    vatNumber: 'CHE-119.553.901 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Temperierung & Giessen dienstags, Versand mittwochs',
    batchScheduleNotice: 'Giesstermin nächste Charge: Dienstag',
    establishedYear: 2022,
    contactEmail: 'atelier@cacao-basel.ch',
    capacityPerBatch: 30,
  },
  {
    id: 'prod-gletscher-gelato',
    name: 'Gletscher Gelato Bern',
    slug: 'gletscher-gelato-bern',
    tagline: 'Artisan Gelato · Kugel für Kugel frisch zusammengestellt',
    category: 'ice_cream',
    country: 'CH',
    city: 'Bern',
    currency: 'CHF',
    bio: 'Täglich frisch gerührtes Gelato aus Berner Bergmilch. Stellen Sie Ihren eigenen Becher aus unseren Sorten und Toppings zusammen — nur zur Abholung, damit nichts schmilzt.',
    heroImage: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=1200&q=80',
    logoText: 'GLETSCHER GELATO — BERN',
    vatNumber: 'CHE-330.774.221 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Täglich frisch gerührt, Abholung ab 11:00 Uhr',
    batchScheduleNotice: 'Heutige Rührung: bereit ab 11:00 Uhr',
    establishedYear: 2023,
    contactEmail: 'ciao@gletscher-gelato.ch',
    capacityPerBatch: 60,
  },
  {
    id: 'prod-zopf-zeit',
    name: 'Bäckerei Zopf & Zeit',
    slug: 'baeckerei-zopf-und-zeit',
    tagline: 'Konditorei für Anlass-Torten nach Mass',
    category: 'bakery',
    country: 'CH',
    city: 'Luzern',
    currency: 'CHF',
    bio: 'Handgefertigte Torten und Festgebäck für besondere Anlässe. Da jede Torte ein Einzelstück ist, arbeiten wir mit persönlicher Offerte statt Sofortkauf.',
    heroImage: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=1200&q=80',
    logoText: 'ZOPF & ZEIT — LUZERN',
    vatNumber: 'CHE-401.882.556 MWST',
    stripeConnected: true,
    leadTimeSchedule: 'Vorlaufzeit mind. 5 Werktage ab Offertannahme',
    batchScheduleNotice: 'Backtag nach individueller Terminvereinbarung',
    establishedYear: 2018,
    contactEmail: 'atelier@zopf-zeit.ch',
  },
];

export const SEED_PRODUCTS: Product[] = [
  // ==========================================
  // BEREICH 1: CUSTOM / MADE-TO-ORDER PRODUKTE
  // ==========================================
  {
    id: 'prod-coffee-custom-blend',
    producerId: 'prod-maelstrom',
    title: 'Signature Custom Coffee Blend (500g)',
    subtitle: 'Kreieren Sie Ihren persönlichen Blend mit Live-Etikett',
    description: 'Kombinieren Sie 4 erstklassige Single Origins per Schieberegler exakt nach Ihrem Geschmacksprofil. Wir wiegen die Rohkaffees auf das Gramm genau ab und rösten sie frisch mit Ihrem persönlichen Etikett.',
    category: 'coffee',
    basePrice: 22.00,
    unitText: '500g Ventilbeutel',
    weightGrams: 500,
    isCustomizable: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['Made to Order', 'Single Origin Blend', 'Spezialitätenkaffee'],
    config: {
      id: 'cfg-coffee-blend',
      productId: 'prod-coffee-custom-blend',
      sliderMode: 'percentage_100',
      targetTotal: 100,
      targetUnit: '%',
      totalWeightGrams: 500,
      sliderTitle: 'Sortenreine Bohnenmischung (100% gesperrt)',
      sliderDescription: 'Verschieben Sie die Anteile. Die Gesamtrezeptur bleibt immer exakt bei 100%.',
      components: [
        {
          id: 'c-ethiopia',
          name: 'Äthiopien Yirgacheffe G1',
          origin: 'Yirgacheffe, 2\'050 m.ü.M.',
          process: 'Washed / Heirloom',
          notes: ['Bergamotte', 'Jasmin', 'Pfirsich'],
          maxRatio: 100,
          priceMultiplier: 1.15,
          color: '#E0A96D',
          inStock: true,
          unitText: '%',
          stockQuantity: 8000,
          costPerUnit: 0.018,
        },
        {
          id: 'c-colombia',
          name: 'Kolumbien Huila Supremo',
          origin: 'San Agustín, 1\'750 m.ü.M.',
          process: 'Washed / Castillo',
          notes: ['Roter Apfel', 'Karamell', 'Milchschokolade'],
          maxRatio: 100,
          priceMultiplier: 1.05,
          color: '#A65335',
          inStock: true,
          unitText: '%',
          stockQuantity: 6500,
          costPerUnit: 0.014,
        },
        {
          id: 'c-brazil',
          name: 'Brasilien Cerrado Dulce',
          origin: 'Minas Gerais, 1\'150 m.ü.M.',
          process: 'Natural / Bourbon',
          notes: ['Haselnuss', 'Kakao', 'Cremiger Körper'],
          maxRatio: 100,
          priceMultiplier: 0.95,
          color: '#633A26',
          inStock: true,
          unitText: '%',
          stockQuantity: 9200,
          costPerUnit: 0.011,
        },
        {
          id: 'c-guatemala',
          name: 'Guatemala Antigua Pastoral',
          origin: 'Volcano Valley, 1\'600 m.ü.M.',
          process: 'Washed / Caturra',
          notes: ['Dunkle Beeren', 'Marzipan', 'Zimt'],
          maxRatio: 100,
          priceMultiplier: 1.10,
          color: '#3F2212',
          inStock: true,
          unitText: '%',
          stockQuantity: 350,
          lowStockThreshold: 500,
          costPerUnit: 0.016,
        },
      ],
      customFields: [
        {
          id: 'f-grind',
          key: 'grind',
          title: 'Mahlgrad & Zubereitung',
          type: 'pills',
          isRequired: true,
          defaultValue: 'whole_bean',
          choices: [
            { id: '1', label: 'Ganze Bohne (Frisch)', value: 'whole_bean', priceDelta: 0, description: 'Optimale Frische & Lagerung' },
            { id: '2', label: 'Espresso (Siebträger)', value: 'espresso', priceDelta: 0, description: 'Fein gemahlen für Siebträger' },
            { id: '3', label: 'Bialetti (Moka)', value: 'moka', priceDelta: 0, description: 'Mittel-fein für Espressokocher' },
            { id: '4', label: 'Filter (V60 / Chemex)', value: 'filter', priceDelta: 0, description: 'Mittel für Handfilter' },
            { id: '5', label: 'French Press', value: 'french_press', priceDelta: 0, description: 'Grob gemahlen' },
          ],
        },
        {
          id: 'f-roast',
          key: 'roast_profile',
          title: 'Röstprofil des Meisters',
          type: 'pills',
          isRequired: true,
          defaultValue: 'omni_medium',
          choices: [
            { id: 'r1', label: 'Nordic Light Roast (Fruchtbetont)', value: 'light_nordic', priceDelta: 0 },
            { id: 'r2', label: 'Omni Medium Roast (Balanciert)', value: 'omni_medium', priceDelta: 0 },
            { id: 'r3', label: 'Italian Dark Roast (Schokoladig & Kräftig)', value: 'dark_italian', priceDelta: 0 },
          ],
        },
      ],
      labelConfig: {
        allowed: true,
        templateType: 'coffee_bag',
        headlinePlaceholder: 'z.B. Julians Morning Fuel',
        maxHeadlineLength: 28,
        allowDedication: true,
        dedicationPlaceholder: 'z.B. Frisch geröstet für das Team Zürich-West',
        maxDedicationLength: 45,
        fixedBrandStamp: '+ SWISS CRAFT · MAELSTROM',
        availableFonts: [
          { id: 'swiss-sans', label: 'Swiss Neo-Grotesk', fontFamily: 'Inter, sans-serif', styleClass: 'font-sans uppercase tracking-widest font-semibold' },
          { id: 'editorial-serif', label: 'Zurich Heritage Serif', fontFamily: 'Playfair Display, serif', styleClass: 'font-serif italic tracking-normal' },
          { id: 'minimal-mono', label: 'Atelier Technical Mono', fontFamily: 'JetBrains Mono, monospace', styleClass: 'font-mono font-medium tracking-tight' },
        ],
      },
    },
  },

  // ==========================================
  // BEREICH 2: NORMALE STANDARD-PRODUKTE
  // ==========================================
  {
    id: 'prod-coffee-standard-geisha',
    producerId: 'prod-maelstrom',
    title: 'Panama Boquete Geisha Lot #4',
    subtitle: 'Limitierte Rarität mit floralem Jasmin-Bouquet',
    description: 'Sortenreiner Geisha-Kaffee aus Panama mit aussergewöhnlicher Klarheit, Bergamotte- und Jasmin-Noten.',
    category: 'coffee',
    basePrice: 34.00,
    unitText: '250g Box',
    weightGrams: 250,
    isCustomizable: false,
    stockQuantity: 42,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80'],
    tags: ['Micro-Lot', 'Single Origin', 'Competition Grade'],
  },
  {
    id: 'prod-coffee-standard-espresso',
    producerId: 'prod-maelstrom',
    title: 'Zürich House Blend Espresso',
    subtitle: 'Klassischer Espresso mit nussig-cremiger Note',
    description: 'Unser bewährter Haus-Espresso aus 70% Brasilien Bourbon und 30% Kolumbien Supremo. Perfekt für Cappuccino und Flat White.',
    category: 'coffee',
    basePrice: 18.50,
    unitText: '500g Beutel',
    weightGrams: 500,
    isCustomizable: false,
    stockQuantity: 120,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80'],
    tags: ['Klassiker', 'Espresso Blend', 'Bestseller'],
  },

  // Craft Beer Custom Box
  {
    id: 'prod-beer-custom-box',
    producerId: 'prod-aarau-hops',
    title: 'Curated 6er Craft Beer Flight & Custom Label',
    subtitle: 'Stellen Sie Ihre 6 Lieblingsflaschen zusammen',
    description: 'Wählen Sie die 6 Flaschen Ihrer Box aus unseren frisch gebrauten Suden. Inklusive individuellem Flaschenetikett.',
    category: 'beer',
    basePrice: 28.50,
    unitText: '6x 330ml Box',
    weightGrams: 1980,
    isCustomizable: true,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1608270199182-96541f53fa38?auto=format&fit=crop&w=800&q=80'],
    tags: ['Craft Beer', 'Unfiltriert', 'Aargau'],
    config: {
      id: 'cfg-beer-box',
      productId: 'prod-beer-custom-box',
      sliderMode: 'percentage_100',
      targetTotal: 100,
      targetUnit: '%',
      totalWeightGrams: 6,
      sliderTitle: 'Flaschenauswahl für 6er Box (100% verteilt)',
      components: [
        { id: 'b-hazy', name: 'Aare Hazy Double IPA (7.2%)', origin: 'Citra Dry Hop', notes: ['Maracuja', 'Grapefruit'], maxRatio: 100, priceMultiplier: 1.12, color: '#EBB344', inStock: true, allergens: ['gluten'], stockQuantity: 180, costPerUnit: 0.012 },
        { id: 'b-pale', name: 'Kettenbrücke Session Pale (4.8%)', origin: 'Hallertau Blanc', notes: ['Stachelbeere', 'Frisch'], maxRatio: 100, priceMultiplier: 0.95, color: '#F4D06F', inStock: true, allergens: ['gluten'], stockQuantity: 240, costPerUnit: 0.009 },
        { id: 'b-sour', name: 'Jura Wild Sour Cherry (5.5%)', origin: 'Sauerkirschen', notes: ['Fruchtsäure', 'Trocken'], maxRatio: 100, priceMultiplier: 1.20, color: '#9C2E35', inStock: true, allergens: ['gluten', 'sulfites'], stockQuantity: 90, costPerUnit: 0.014 },
        { id: 'b-porter', name: 'Altstadt Smoked Porter (6.8%)', origin: 'Rauchmalz', notes: ['Bitterschokolade', 'Rauch'], maxRatio: 100, priceMultiplier: 1.05, color: '#261C14', inStock: true, allergens: ['gluten'], stockQuantity: 0, costPerUnit: 0.011 },
      ],
      customFields: [
        {
          id: 'f-box',
          key: 'packaging',
          title: 'Verpackungsausführung',
          type: 'pills',
          isRequired: true,
          defaultValue: 'kraft',
          choices: [
            { id: 'p1', label: 'Design Kraftkarton Box', value: 'kraft', priceDelta: 0 },
            { id: 'p2', label: 'Rustikale Schweizer Holzkiste (+ CHF 8.00)', value: 'wood', priceDelta: 8.0 },
          ],
        },
      ],
      labelConfig: {
        allowed: true,
        templateType: 'beer_bottle',
        headlinePlaceholder: 'z.B. Summer Solstice Sud #08',
        maxHeadlineLength: 25,
        allowDedication: true,
        dedicationPlaceholder: 'z.B. Für das Grillfest am Aareufer',
        maxDedicationLength: 40,
        fixedBrandStamp: '+ SWISS CRAFT · AARAU HOPS',
        availableFonts: [
          { id: 'swiss-sans', label: 'Swiss Modern', fontFamily: 'Inter, sans-serif', styleClass: 'font-sans uppercase font-bold' },
          { id: 'minimal-mono', label: 'Brewery Mono', fontFamily: 'JetBrains Mono, monospace', styleClass: 'font-mono' },
        ],
      },
    },
  },

  // Ice Cream Build-a-Box (free_quantity archetype, pickup only)
  {
    id: 'prod-gelato-custom-cup',
    producerId: 'prod-gletscher-gelato',
    title: 'Build-Your-Own Gelato Becher',
    subtitle: 'Kugeln & Toppings frei kombinieren',
    description: 'Wählen Sie Ihre Lieblingskugeln und Toppings frisch aus der heutigen Rührung. Nur zur Abholung, damit alles perfekt gefroren bleibt.',
    category: 'ice_cream',
    basePrice: 6.50,
    unitText: 'Becher (3 Kugeln)',
    weightGrams: 240,
    isCustomizable: true,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80'],
    tags: ['Made to Order', 'Nur Abholung'],
    transactionMode: 'instant_checkout',
    shippingRestriction: 'pickup_only',
    allergens: [],
    config: {
      id: 'cfg-gelato-cup',
      productId: 'prod-gelato-custom-cup',
      archetype: 'build_a_box',
      sliderMode: 'free_quantity',
      targetTotal: 3,
      targetUnit: 'Kugeln',
      totalWeightGrams: 240,
      sliderTitle: 'Kugelauswahl (max. 3 Kugeln inklusive)',
      sliderDescription: 'Stellen Sie bis zu 3 Kugeln aus unseren Tagessorten zusammen.',
      components: [
        { id: 'g-pistazie', name: 'Sizilianische Pistazie', notes: ['Nussig', 'Cremig'], maxRatio: 3, priceMultiplier: 1.1, color: '#9CAF6B', inStock: true, unitText: 'Kugeln', allergens: ['milk', 'nuts'], stockQuantity: 40, costPerUnit: 0.9 },
        { id: 'g-fragola', name: 'Fragola di Bosco (Walderdbeere)', notes: ['Fruchtig', 'Vegan'], maxRatio: 3, priceMultiplier: 1.0, color: '#C94F5C', inStock: true, unitText: 'Kugeln', allergens: [], stockQuantity: 55, costPerUnit: 0.6 },
        { id: 'g-stracciatella', name: 'Stracciatella', notes: ['Cremig', 'Schokosplitter'], maxRatio: 3, priceMultiplier: 1.05, color: '#F4F1E8', inStock: true, unitText: 'Kugeln', allergens: ['milk'], stockQuantity: 60, costPerUnit: 0.7 },
      ],
      customFields: [
        {
          id: 'f-topping',
          key: 'topping',
          title: 'Topping',
          type: 'pills',
          isRequired: false,
          defaultValue: 'none',
          choices: [
            { id: 't0', label: 'Ohne Topping', value: 'none', priceDelta: 0 },
            { id: 't1', label: 'Geröstete Haselnüsse', value: 'hazelnut', priceDelta: 1.0, allergens: ['nuts'] },
            { id: 't2', label: 'Schokoladensauce', value: 'chocolate', priceDelta: 1.0, allergens: ['milk', 'soy'] },
          ],
        },
      ],
      labelConfig: {
        allowed: true,
        templateType: 'modern_minimal',
        headlinePlaceholder: 'z.B. Sommerabend Special',
        maxHeadlineLength: 24,
        allowDedication: false,
        maxDedicationLength: 0,
        fixedBrandStamp: '+ SWISS CRAFT · GLETSCHER GELATO',
        availableFonts: [
          { id: 'swiss-sans', label: 'Swiss Modern', fontFamily: 'Inter, sans-serif', styleClass: 'font-sans font-bold' },
        ],
      },
    },
  },

  // Bespoke bakery product — quote_request only, no slider, pure custom fields
  {
    id: 'prod-bakery-custom-cake',
    producerId: 'prod-zopf-zeit',
    title: 'Anlass-Torte nach Mass',
    subtitle: 'Individuelle Offerte für Ihre Feier',
    description: 'Jede Torte wird als Einzelstück nach Ihren Vorgaben gebacken. Senden Sie uns Grösse, Geschmack und Anlass — wir melden uns mit einer persönlichen Offerte.',
    category: 'bakery',
    basePrice: 0,
    unitText: 'Individuelle Grösse',
    weightGrams: 0,
    isCustomizable: true,
    isActive: true,
    images: ['https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=800&q=80'],
    tags: ['Nur auf Anfrage', 'Einzelstück'],
    transactionMode: 'quote_request',
    shippingRestriction: 'pickup_only',
    allergens: ['gluten', 'eggs', 'milk'],
    config: {
      id: 'cfg-bakery-cake',
      productId: 'prod-bakery-custom-cake',
      archetype: 'bespoke',
      sliderMode: 'free_quantity',
      targetTotal: 0,
      targetUnit: '',
      totalWeightGrams: 0,
      sliderTitle: 'Keine Rezeptur — nur Zusatzfelder',
      components: [],
      customFields: [
        {
          id: 'f-size',
          key: 'size',
          title: 'Grösse / Anzahl Personen',
          type: 'select',
          isRequired: true,
          defaultValue: 'medium',
          choices: [
            { id: 's1', label: 'Klein (ca. 8 Personen)', value: 'small', priceDelta: 0 },
            { id: 's2', label: 'Mittel (ca. 16 Personen)', value: 'medium', priceDelta: 0 },
            { id: 's3', label: 'Gross (ca. 30 Personen)', value: 'large', priceDelta: 0 },
          ],
        },
        {
          id: 'f-occasion',
          key: 'occasion',
          title: 'Anlass',
          type: 'text',
          isRequired: true,
          maxCharacters: 60,
          placeholder: 'z.B. Hochzeit, Geburtstag, Firmenfeier',
        },
        {
          id: 'f-wish',
          key: 'wish_text',
          title: 'Wunschtext auf der Torte',
          type: 'text',
          isRequired: false,
          maxCharacters: 40,
          placeholder: 'z.B. Herzlichen Glückwunsch!',
        },
      ],
      labelConfig: {
        allowed: false,
        templateType: 'custom_box',
        headlinePlaceholder: '',
        maxHeadlineLength: 0,
        allowDedication: false,
        maxDedicationLength: 0,
        fixedBrandStamp: '+ SWISS CRAFT · ZOPF & ZEIT',
        availableFonts: [],
      },
    },
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'ATL-2026-8801',
    producerId: 'prod-maelstrom',
    producerName: 'Maelstrom Roasters',
    customer: {
      name: 'Marc Oberholzer',
      email: 'marc.oberholzer@bluewin.ch',
      street: 'Hardturmstrasse 130',
      postalCode: '8005',
      city: 'Zürich',
      country: 'CH',
    },
    items: [
      {
        id: 'item-1',
        productId: 'prod-coffee-custom-blend',
        productTitle: 'Signature Custom Coffee Blend (500g)',
        quantity: 2,
        unitPrice: 24.20,
        totalPrice: 48.40,
        weightGrams: 500,
        isCustomItem: true,
        recipe: [
          { componentId: 'c-ethiopia', componentName: 'Äthiopien Yirgacheffe G1', origin: 'Yirgacheffe', ratio: 60, grams: 300 },
          { componentId: 'c-colombia', componentName: 'Kolumbien Huila Supremo', origin: 'San Agustín', ratio: 40, grams: 200 },
        ],
        customFieldValues: {
          grind: 'espresso',
          roast_profile: 'omni_medium',
        },
        customLabel: {
          headline: 'Marc’s Morning Fuel',
          subtitle: '60% Yirgacheffe / 40% Huila',
          dedication: 'Frisch geröstet für das Team Zürich-West',
          fontStyle: 'swiss-sans',
          batchNumber: 'MZ-BATCH #441',
          roastOrBrewDate: '19.08.2026',
        },
      },
    ],
    status: 'in_production',
    currency: 'CHF',
    subtotal: 48.40,
    taxRate: 0.081,
    taxAmount: 3.92,
    total: 48.40,
    fulfillmentType: 'shipping',
    paymentMethod: 'twint',
    paymentStatus: 'paid',
    createdAt: '2026-08-16T14:22:00Z',
    scheduledBatchDate: '2026-08-18',
  },
];
